---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: heartbeat-kubeadm-config
  namespace: monitoring
  labels:
    k8s-app: heartbeat
rules:
  - apiGroups: ['']
    resources: ['*']
    resourceNames:
      - kubeadm-config
    verbs: [get]
