---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heartbeat
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: heartbeat
    namespace: monitoring
roleRef:
  kind: Role
  name: heartbeat
  apiGroup: rbac.authorization.k8s.io
